/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-north-1",
    "aws_appsync_graphqlEndpoint": "https://naawkpttsjc2zjdbzg2uoyqfvi.appsync-api.eu-north-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-north-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-h57rxnsh4vdq5ezir36t5sf3tm",
    "aws_cognito_identity_pool_id": "eu-north-1:8cbbbdf7-60d5-4a82-8574-5da68c19bddb",
    "aws_cognito_region": "eu-north-1",
    "aws_user_pools_id": "eu-north-1_Q2ea1FZpH",
    "aws_user_pools_web_client_id": "498dr2ro6fbm2pg5uqb1532e8j",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL",
        "PHONE_NUMBER"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
